// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportEventManager.Data.Persistence;

#nullable disable

namespace SportEventManager.Migrations
{
    [DbContext(typeof(SportEventDbContext))]
    [Migration("20251006214606_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SportEventManager.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxAge")
                        .HasColumnType("int");

                    b.Property<int>("MinAge")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Gender = "Ambos",
                            MaxAge = 99,
                            MinAge = 18,
                            Name = "Absoluto",
                            RaceId = 1
                        },
                        new
                        {
                            CategoryId = 2,
                            Gender = "Femenino",
                            MaxAge = 99,
                            MinAge = 18,
                            Name = "Femenino",
                            RaceId = 2
                        });
                });

            modelBuilder.Entity("SportEventManager.Models.Chip", b =>
                {
                    b.Property<int>("ChipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChipId"));

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ChipId");

                    b.ToTable("Chips");

                    b.HasData(
                        new
                        {
                            ChipId = 1,
                            SerialNumber = "CHIP1234"
                        },
                        new
                        {
                            ChipId = 2,
                            SerialNumber = "CHIP5678"
                        });
                });

            modelBuilder.Entity("SportEventManager.Models.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("EventId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            EventId = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Una carrera de larga distancia a nivel internacional.",
                            EndDate = new DateTime(2025, 3, 10, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Ciudad Central",
                            MaxParticipants = 5000,
                            Name = "Maratón Internacional",
                            StartDate = new DateTime(2025, 3, 10, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EventId = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Competencia rápida en la ciudad.",
                            EndDate = new DateTime(2025, 4, 5, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Parque Nacional",
                            MaxParticipants = 1000,
                            Name = "Carrera de 5K",
                            StartDate = new DateTime(2025, 4, 5, 7, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("SportEventManager.Models.Participant", b =>
                {
                    b.Property<int>("ParticipantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParticipantId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ParticipantId");

                    b.ToTable("Participants");

                    b.HasData(
                        new
                        {
                            ParticipantId = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DocumentNumber = "12345678",
                            Email = "juan.perez@email.com",
                            FirstName = "Juan",
                            LastName = "Pérez"
                        },
                        new
                        {
                            ParticipantId = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DocumentNumber = "87654321",
                            Email = "ana.gomez@email.com",
                            FirstName = "Ana",
                            LastName = "Gómez"
                        });
                });

            modelBuilder.Entity("SportEventManager.Models.Race", b =>
                {
                    b.Property<int>("RaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RaceId"));

                    b.Property<double>("DistanceKm")
                        .HasColumnType("float");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("RaceId");

                    b.ToTable("Races");

                    b.HasData(
                        new
                        {
                            RaceId = 1,
                            DistanceKm = 42.0,
                            EventId = 1,
                            Name = "Maratón 42K",
                            StartTime = new DateTime(2025, 3, 10, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            RaceId = 2,
                            DistanceKm = 5.0,
                            EventId = 2,
                            Name = "Carrera 5K",
                            StartTime = new DateTime(2025, 4, 5, 7, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("SportEventManager.Models.Registration", b =>
                {
                    b.Property<int>("RegistrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegistrationId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("int");

                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RegistrationId");

                    b.ToTable("Registrations");

                    b.HasData(
                        new
                        {
                            RegistrationId = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParticipantId = 1,
                            RaceId = 1,
                            Status = "Pending"
                        },
                        new
                        {
                            RegistrationId = 2,
                            CategoryId = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParticipantId = 2,
                            RaceId = 2,
                            Status = "Confirmed"
                        });
                });

            modelBuilder.Entity("SportEventManager.Models.RegistrationChip", b =>
                {
                    b.Property<int>("RegistrationChipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegistrationChipId"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ChipId")
                        .HasColumnType("int");

                    b.Property<int>("RegistrationId")
                        .HasColumnType("int");

                    b.HasKey("RegistrationChipId");

                    b.ToTable("RegistrationChips");

                    b.HasData(
                        new
                        {
                            RegistrationChipId = 1,
                            AssignedAt = new DateTime(2025, 3, 10, 7, 30, 0, 0, DateTimeKind.Unspecified),
                            ChipId = 1,
                            RegistrationId = 1
                        },
                        new
                        {
                            RegistrationChipId = 2,
                            AssignedAt = new DateTime(2025, 4, 5, 6, 30, 0, 0, DateTimeKind.Unspecified),
                            ChipId = 2,
                            RegistrationId = 2
                        });
                });

            modelBuilder.Entity("SportEventManager.Models.Split", b =>
                {
                    b.Property<int>("SplitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SplitId"));

                    b.Property<double>("KmMark")
                        .HasColumnType("float");

                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.Property<string>("SplitName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SplitId");

                    b.ToTable("Splits");

                    b.HasData(
                        new
                        {
                            SplitId = 1,
                            KmMark = 1.0,
                            RaceId = 1,
                            SplitName = "Primer Kilómetro"
                        },
                        new
                        {
                            SplitId = 2,
                            KmMark = 1.0,
                            RaceId = 2,
                            SplitName = "Primer Kilómetro"
                        });
                });

            modelBuilder.Entity("SportEventManager.Models.TimeRecord", b =>
                {
                    b.Property<int>("TimeRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TimeRecordId"));

                    b.Property<int>("ChipId")
                        .HasColumnType("int");

                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.Property<int>("SplitId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("TimeRecordId");

                    b.ToTable("TimeRecords");

                    b.HasData(
                        new
                        {
                            TimeRecordId = 1,
                            ChipId = 1,
                            RaceId = 1,
                            SplitId = 1,
                            Timestamp = new DateTime(2025, 3, 10, 8, 5, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRecordId = 2,
                            ChipId = 2,
                            RaceId = 2,
                            SplitId = 2,
                            Timestamp = new DateTime(2025, 4, 5, 7, 10, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
