// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportEventManager.Data.Persistence;

#nullable disable

namespace SportEventManager.Migrations
{
    [DbContext(typeof(SportEventDbContext))]
    [Migration("20251015170003_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SportEventManager.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("MaxAge")
                        .HasColumnType("int");

                    b.Property<int?>("MinAge")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.HasIndex("Name");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("SportEventManager.Models.Chip", b =>
                {
                    b.Property<int>("ChipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChipId"));

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ChipId");

                    b.ToTable("Chips");
                });

            modelBuilder.Entity("SportEventManager.Models.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("EventId");

                    b.HasIndex("Name");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("SportEventManager.Models.Participant", b =>
                {
                    b.Property<int>("ParticipantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParticipantId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ParticipantId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("LastName", "FirstName");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("SportEventManager.Models.Race", b =>
                {
                    b.Property<int>("RaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RaceId"));

                    b.Property<double>("DistanceKm")
                        .HasColumnType("float");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("RaceId");

                    b.HasIndex("EventId");

                    b.HasIndex("Name");

                    b.ToTable("Races");
                });

            modelBuilder.Entity("SportEventManager.Models.RaceCategory", b =>
                {
                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("RaceId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("RaceCategories");
                });

            modelBuilder.Entity("SportEventManager.Models.Registration", b =>
                {
                    b.Property<int>("RegistrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegistrationId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("int");

                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("RegistrationId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("RaceId");

                    b.ToTable("Registrations");
                });

            modelBuilder.Entity("SportEventManager.Models.RegistrationChip", b =>
                {
                    b.Property<int>("RegistrationChipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegistrationChipId"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ChipId")
                        .HasColumnType("int");

                    b.Property<int>("RegistrationId")
                        .HasColumnType("int");

                    b.HasKey("RegistrationChipId");

                    b.HasIndex("ChipId");

                    b.HasIndex("RegistrationId");

                    b.ToTable("RegistrationChips");
                });

            modelBuilder.Entity("SportEventManager.Models.Split", b =>
                {
                    b.Property<int>("SplitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SplitId"));

                    b.Property<double?>("KmMark")
                        .HasColumnType("float");

                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.Property<string>("SplitName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SplitId");

                    b.HasIndex("RaceId");

                    b.ToTable("Splits");
                });

            modelBuilder.Entity("SportEventManager.Models.TimeRecord", b =>
                {
                    b.Property<int>("TimeRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TimeRecordId"));

                    b.Property<int>("ChipId")
                        .HasColumnType("int");

                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.Property<int>("SplitId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("TimeRecordId");

                    b.HasIndex("ChipId");

                    b.HasIndex("RaceId");

                    b.HasIndex("SplitId");

                    b.ToTable("TimeRecords");
                });

            modelBuilder.Entity("SportEventManager.Models.Race", b =>
                {
                    b.HasOne("SportEventManager.Models.Event", null)
                        .WithMany("Races")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SportEventManager.Models.RaceCategory", b =>
                {
                    b.HasOne("SportEventManager.Models.Category", "Category")
                        .WithMany("RaceCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportEventManager.Models.Race", "Race")
                        .WithMany("RaceCategories")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("SportEventManager.Models.Registration", b =>
                {
                    b.HasOne("SportEventManager.Models.Category", "Category")
                        .WithMany("Registrations")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportEventManager.Models.Participant", "Participant")
                        .WithMany("Registrations")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportEventManager.Models.Race", "Race")
                        .WithMany("Registrations")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Participant");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("SportEventManager.Models.RegistrationChip", b =>
                {
                    b.HasOne("SportEventManager.Models.Chip", "Chip")
                        .WithMany("RegistrationChip")
                        .HasForeignKey("ChipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportEventManager.Models.Registration", "Registration")
                        .WithMany("RegistrationChips")
                        .HasForeignKey("RegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chip");

                    b.Navigation("Registration");
                });

            modelBuilder.Entity("SportEventManager.Models.Split", b =>
                {
                    b.HasOne("SportEventManager.Models.Race", "Race")
                        .WithMany("Splits")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Race");
                });

            modelBuilder.Entity("SportEventManager.Models.TimeRecord", b =>
                {
                    b.HasOne("SportEventManager.Models.Chip", "Chip")
                        .WithMany("TimeRecord")
                        .HasForeignKey("ChipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportEventManager.Models.Race", "Race")
                        .WithMany("TimeRecords")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportEventManager.Models.Split", "Split")
                        .WithMany("TimeRecord")
                        .HasForeignKey("SplitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chip");

                    b.Navigation("Race");

                    b.Navigation("Split");
                });

            modelBuilder.Entity("SportEventManager.Models.Category", b =>
                {
                    b.Navigation("RaceCategories");

                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("SportEventManager.Models.Chip", b =>
                {
                    b.Navigation("RegistrationChip");

                    b.Navigation("TimeRecord");
                });

            modelBuilder.Entity("SportEventManager.Models.Event", b =>
                {
                    b.Navigation("Races");
                });

            modelBuilder.Entity("SportEventManager.Models.Participant", b =>
                {
                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("SportEventManager.Models.Race", b =>
                {
                    b.Navigation("RaceCategories");

                    b.Navigation("Registrations");

                    b.Navigation("Splits");

                    b.Navigation("TimeRecords");
                });

            modelBuilder.Entity("SportEventManager.Models.Registration", b =>
                {
                    b.Navigation("RegistrationChips");
                });

            modelBuilder.Entity("SportEventManager.Models.Split", b =>
                {
                    b.Navigation("TimeRecord");
                });
#pragma warning restore 612, 618
        }
    }
}
