// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportEventManager.Data.Persistence;

#nullable disable

namespace SportEventManager.Migrations
{
    [DbContext(typeof(SportEventDbContext))]
    [Migration("20251101011357_AddParticipantDobAndGender")]
    partial class AddParticipantDobAndGender
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SportEventManager.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("ExternalName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("InternalName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaxAge")
                        .HasColumnType("int");

                    b.Property<int?>("MinAge")
                        .HasColumnType("int");

                    b.HasKey("CategoryId");

                    b.HasIndex("InternalName");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            ExternalName = "Caballeros Mayores (18 años o más)",
                            Gender = "M",
                            InternalName = "Caballeros - Mayores",
                            MinAge = 18
                        },
                        new
                        {
                            CategoryId = 2,
                            ExternalName = "Damas Mayores (18 años o más)",
                            Gender = "F",
                            InternalName = "Damas - Mayores",
                            MinAge = 18
                        },
                        new
                        {
                            CategoryId = 3,
                            ExternalName = "Mixtos Mayores",
                            Gender = "X",
                            InternalName = "Mixtos - Mayores",
                            MinAge = 18
                        },
                        new
                        {
                            CategoryId = 4,
                            ExternalName = "Juveniles (12 - 17 años)",
                            Gender = "X",
                            InternalName = "Juveniles - Mixtos",
                            MaxAge = 17,
                            MinAge = 12
                        },
                        new
                        {
                            CategoryId = 5,
                            ExternalName = "Infantiles (hasta 11 años)",
                            Gender = "X",
                            InternalName = "Infantiles",
                            MaxAge = 11,
                            MinAge = 0
                        });
                });

            modelBuilder.Entity("SportEventManager.Models.Chip", b =>
                {
                    b.Property<int>("ChipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChipId"));

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ChipId");

                    b.ToTable("Chips");

                    b.HasData(
                        new
                        {
                            ChipId = 1,
                            SerialNumber = "CHIP-001"
                        },
                        new
                        {
                            ChipId = 2,
                            SerialNumber = "CHIP-002"
                        },
                        new
                        {
                            ChipId = 3,
                            SerialNumber = "CHIP-003"
                        },
                        new
                        {
                            ChipId = 4,
                            SerialNumber = "CHIP-004"
                        },
                        new
                        {
                            ChipId = 5,
                            SerialNumber = "CHIP-005"
                        },
                        new
                        {
                            ChipId = 6,
                            SerialNumber = "CHIP-006"
                        },
                        new
                        {
                            ChipId = 7,
                            SerialNumber = "CHIP-007"
                        },
                        new
                        {
                            ChipId = 8,
                            SerialNumber = "CHIP-008"
                        },
                        new
                        {
                            ChipId = 9,
                            SerialNumber = "CHIP-009"
                        },
                        new
                        {
                            ChipId = 10,
                            SerialNumber = "CHIP-010"
                        });
                });

            modelBuilder.Entity("SportEventManager.Models.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("EventId");

                    b.HasIndex("Name");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            EventId = 1,
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Maratón de 10K y 5K",
                            EndDate = new DateTime(2025, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Montevideo",
                            Name = "Maratón Anual",
                            StartDate = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EventId = 2,
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Una carrera en Piria",
                            EndDate = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "",
                            Name = "Recorre Maldonado 8va etapa",
                            StartDate = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EventId = 3,
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Última etapa de Recorre Maldonado. ",
                            EndDate = new DateTime(2026, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Maldonado",
                            Name = "Recorre Maldonado 9na etapa",
                            StartDate = new DateTime(2025, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EventId = 4,
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Primera carrera del año en Punta",
                            EndDate = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Punta del Este",
                            Name = "San Fernando 2026",
                            StartDate = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EventId = 5,
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Media Maratón anual de Montevideo.",
                            EndDate = new DateTime(2026, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Montevideo",
                            Name = "Half Marathon",
                            StartDate = new DateTime(2026, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("SportEventManager.Models.Participant", b =>
                {
                    b.Property<int>("ParticipantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParticipantId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ParticipantId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("LastName", "FirstName");

                    b.ToTable("Participants");

                    b.HasData(
                        new
                        {
                            ParticipantId = 1,
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1990, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DocumentNumber = "12345678",
                            Email = "matias@test.com",
                            FirstName = "Matias",
                            Gender = "Masculino",
                            LastName = "Alfaro"
                        },
                        new
                        {
                            ParticipantId = 2,
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1992, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DocumentNumber = "87654321",
                            Email = "ana@test.com",
                            FirstName = "Ana",
                            Gender = "Femenino",
                            LastName = "Gomez"
                        },
                        new
                        {
                            ParticipantId = 3,
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1988, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DocumentNumber = "11223344",
                            Email = "lucas@test.com",
                            FirstName = "Lucas",
                            Gender = "Masculino",
                            LastName = "Perez"
                        },
                        new
                        {
                            ParticipantId = 4,
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1995, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DocumentNumber = "44332211",
                            Email = "sofia@test.com",
                            FirstName = "Sofia",
                            Gender = "Femenino",
                            LastName = "Martinez"
                        },
                        new
                        {
                            ParticipantId = 5,
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1985, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DocumentNumber = "55667788",
                            Email = "juan@test.com",
                            FirstName = "Juan",
                            Gender = "Masculino",
                            LastName = "Diaz"
                        },
                        new
                        {
                            ParticipantId = 6,
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1994, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DocumentNumber = "99887766",
                            Email = "lucia@test.com",
                            FirstName = "Lucia",
                            Gender = "Femenino",
                            LastName = "Fernandez"
                        },
                        new
                        {
                            ParticipantId = 7,
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1989, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DocumentNumber = "66778899",
                            Email = "carlos@test.com",
                            FirstName = "Carlos",
                            Gender = "Masculino",
                            LastName = "Rojas"
                        },
                        new
                        {
                            ParticipantId = 8,
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1993, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DocumentNumber = "77889900",
                            Email = "laura@test.com",
                            FirstName = "Laura",
                            Gender = "Femenino",
                            LastName = "Vazquez"
                        },
                        new
                        {
                            ParticipantId = 9,
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1987, 6, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DocumentNumber = "33445566",
                            Email = "pedro@test.com",
                            FirstName = "Pedro",
                            Gender = "Masculino",
                            LastName = "Torres"
                        },
                        new
                        {
                            ParticipantId = 10,
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1991, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DocumentNumber = "22334455",
                            Email = "mariana@test.com",
                            FirstName = "Mariana",
                            Gender = "Femenino",
                            LastName = "Suarez"
                        });
                });

            modelBuilder.Entity("SportEventManager.Models.Race", b =>
                {
                    b.Property<int>("RaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RaceId"));

                    b.Property<double>("DistanceKm")
                        .HasColumnType("float");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("RaceId");

                    b.HasIndex("EventId");

                    b.HasIndex("Name");

                    b.ToTable("Races");

                    b.HasData(
                        new
                        {
                            RaceId = 1,
                            DistanceKm = 10.0,
                            EventId = 1,
                            MaxParticipants = 100,
                            Name = "10K Adultos",
                            StartTime = new DateTime(2025, 12, 1, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            RaceId = 2,
                            DistanceKm = 5.0,
                            EventId = 1,
                            MaxParticipants = 80,
                            Name = "5K Junior",
                            StartTime = new DateTime(2025, 12, 1, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            RaceId = 3,
                            DistanceKm = 10.0,
                            EventId = 2,
                            MaxParticipants = 1000,
                            Name = "10K",
                            StartTime = new DateTime(2025, 11, 8, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            RaceId = 4,
                            DistanceKm = 5.0,
                            EventId = 2,
                            MaxParticipants = 1000,
                            Name = "5 k",
                            StartTime = new DateTime(2025, 11, 8, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            RaceId = 5,
                            DistanceKm = 10.0,
                            EventId = 3,
                            MaxParticipants = 1000,
                            Name = "10k",
                            StartTime = new DateTime(2025, 11, 29, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            RaceId = 6,
                            DistanceKm = 5.0,
                            EventId = 3,
                            MaxParticipants = 1000,
                            Name = "5k",
                            StartTime = new DateTime(2025, 11, 29, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            RaceId = 7,
                            DistanceKm = 10.0,
                            EventId = 4,
                            MaxParticipants = 4500,
                            Name = "10k",
                            StartTime = new DateTime(2026, 1, 10, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            RaceId = 8,
                            DistanceKm = 5.0,
                            EventId = 4,
                            MaxParticipants = 4500,
                            Name = "5k",
                            StartTime = new DateTime(2026, 1, 10, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            RaceId = 9,
                            DistanceKm = 2.0,
                            EventId = 4,
                            MaxParticipants = 1000,
                            Name = "San Fernandito",
                            StartTime = new DateTime(2026, 1, 10, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            RaceId = 10,
                            DistanceKm = 21.0,
                            EventId = 5,
                            MaxParticipants = 4500,
                            Name = "21k",
                            StartTime = new DateTime(2026, 8, 3, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("SportEventManager.Models.RaceCategory", b =>
                {
                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("RaceId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("RaceCategories");

                    b.HasData(
                        new
                        {
                            RaceId = 1,
                            CategoryId = 3
                        },
                        new
                        {
                            RaceId = 2,
                            CategoryId = 3
                        },
                        new
                        {
                            RaceId = 2,
                            CategoryId = 4
                        });
                });

            modelBuilder.Entity("SportEventManager.Models.Registration", b =>
                {
                    b.Property<int>("RegistrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegistrationId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("int");

                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("RegistrationId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("RaceId");

                    b.ToTable("Registrations");

                    b.HasData(
                        new
                        {
                            RegistrationId = 1,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParticipantId = 1,
                            RaceId = 1,
                            Status = "Confirmed"
                        },
                        new
                        {
                            RegistrationId = 2,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParticipantId = 2,
                            RaceId = 1,
                            Status = "Confirmed"
                        },
                        new
                        {
                            RegistrationId = 3,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParticipantId = 3,
                            RaceId = 2,
                            Status = "Pending"
                        },
                        new
                        {
                            RegistrationId = 4,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParticipantId = 4,
                            RaceId = 2,
                            Status = "Pending"
                        },
                        new
                        {
                            RegistrationId = 5,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParticipantId = 5,
                            RaceId = 1,
                            Status = "Confirmed"
                        },
                        new
                        {
                            RegistrationId = 6,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParticipantId = 6,
                            RaceId = 1,
                            Status = "Confirmed"
                        },
                        new
                        {
                            RegistrationId = 7,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParticipantId = 7,
                            RaceId = 2,
                            Status = "Pending"
                        },
                        new
                        {
                            RegistrationId = 8,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParticipantId = 8,
                            RaceId = 2,
                            Status = "Pending"
                        },
                        new
                        {
                            RegistrationId = 9,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParticipantId = 9,
                            RaceId = 1,
                            Status = "Confirmed"
                        },
                        new
                        {
                            RegistrationId = 10,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParticipantId = 10,
                            RaceId = 1,
                            Status = "Confirmed"
                        });
                });

            modelBuilder.Entity("SportEventManager.Models.RegistrationChip", b =>
                {
                    b.Property<int>("RegistrationChipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegistrationChipId"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ChipId")
                        .HasColumnType("int");

                    b.Property<int>("RegistrationId")
                        .HasColumnType("int");

                    b.HasKey("RegistrationChipId");

                    b.HasIndex("ChipId");

                    b.HasIndex("RegistrationId");

                    b.ToTable("RegistrationChips");

                    b.HasData(
                        new
                        {
                            RegistrationChipId = 1,
                            AssignedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ChipId = 1,
                            RegistrationId = 1
                        },
                        new
                        {
                            RegistrationChipId = 2,
                            AssignedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ChipId = 2,
                            RegistrationId = 2
                        },
                        new
                        {
                            RegistrationChipId = 3,
                            AssignedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ChipId = 3,
                            RegistrationId = 3
                        },
                        new
                        {
                            RegistrationChipId = 4,
                            AssignedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ChipId = 4,
                            RegistrationId = 4
                        },
                        new
                        {
                            RegistrationChipId = 5,
                            AssignedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ChipId = 5,
                            RegistrationId = 5
                        },
                        new
                        {
                            RegistrationChipId = 6,
                            AssignedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ChipId = 6,
                            RegistrationId = 6
                        },
                        new
                        {
                            RegistrationChipId = 7,
                            AssignedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ChipId = 7,
                            RegistrationId = 7
                        },
                        new
                        {
                            RegistrationChipId = 8,
                            AssignedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ChipId = 8,
                            RegistrationId = 8
                        },
                        new
                        {
                            RegistrationChipId = 9,
                            AssignedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ChipId = 9,
                            RegistrationId = 9
                        },
                        new
                        {
                            RegistrationChipId = 10,
                            AssignedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ChipId = 10,
                            RegistrationId = 10
                        });
                });

            modelBuilder.Entity("SportEventManager.Models.Split", b =>
                {
                    b.Property<int>("SplitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SplitId"));

                    b.Property<double?>("KmMark")
                        .HasColumnType("float");

                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.Property<string>("SplitName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SplitId");

                    b.HasIndex("RaceId");

                    b.ToTable("Splits");

                    b.HasData(
                        new
                        {
                            SplitId = 1,
                            KmMark = 5.0,
                            RaceId = 1,
                            SplitName = "Km 5"
                        },
                        new
                        {
                            SplitId = 2,
                            KmMark = 10.0,
                            RaceId = 1,
                            SplitName = "Km 10"
                        },
                        new
                        {
                            SplitId = 3,
                            KmMark = 2.5,
                            RaceId = 2,
                            SplitName = "Km 2.5"
                        },
                        new
                        {
                            SplitId = 4,
                            KmMark = 5.0,
                            RaceId = 2,
                            SplitName = "Km 5"
                        });
                });

            modelBuilder.Entity("SportEventManager.Models.TimeRecord", b =>
                {
                    b.Property<int>("TimeRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TimeRecordId"));

                    b.Property<int>("ChipId")
                        .HasColumnType("int");

                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.Property<int>("SplitId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("TimeRecordId");

                    b.HasIndex("ChipId");

                    b.HasIndex("RaceId");

                    b.HasIndex("SplitId");

                    b.ToTable("TimeRecords");

                    b.HasData(
                        new
                        {
                            TimeRecordId = 1,
                            ChipId = 1,
                            RaceId = 1,
                            SplitId = 1,
                            Timestamp = new DateTime(2025, 10, 15, 8, 5, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRecordId = 2,
                            ChipId = 2,
                            RaceId = 1,
                            SplitId = 2,
                            Timestamp = new DateTime(2025, 10, 15, 8, 10, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRecordId = 3,
                            ChipId = 3,
                            RaceId = 2,
                            SplitId = 3,
                            Timestamp = new DateTime(2025, 10, 15, 8, 15, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRecordId = 4,
                            ChipId = 4,
                            RaceId = 2,
                            SplitId = 4,
                            Timestamp = new DateTime(2025, 10, 15, 8, 20, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("SportEventManager.Models.Race", b =>
                {
                    b.HasOne("SportEventManager.Models.Event", null)
                        .WithMany("Races")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SportEventManager.Models.RaceCategory", b =>
                {
                    b.HasOne("SportEventManager.Models.Category", "Category")
                        .WithMany("RaceCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportEventManager.Models.Race", "Race")
                        .WithMany("RaceCategories")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("SportEventManager.Models.Registration", b =>
                {
                    b.HasOne("SportEventManager.Models.Category", "Category")
                        .WithMany("Registrations")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportEventManager.Models.Participant", "Participant")
                        .WithMany("Registrations")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportEventManager.Models.Race", "Race")
                        .WithMany("Registrations")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Participant");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("SportEventManager.Models.RegistrationChip", b =>
                {
                    b.HasOne("SportEventManager.Models.Chip", "Chip")
                        .WithMany("RegistrationChip")
                        .HasForeignKey("ChipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportEventManager.Models.Registration", "Registration")
                        .WithMany("RegistrationChips")
                        .HasForeignKey("RegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chip");

                    b.Navigation("Registration");
                });

            modelBuilder.Entity("SportEventManager.Models.Split", b =>
                {
                    b.HasOne("SportEventManager.Models.Race", "Race")
                        .WithMany("Splits")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Race");
                });

            modelBuilder.Entity("SportEventManager.Models.TimeRecord", b =>
                {
                    b.HasOne("SportEventManager.Models.Chip", "Chip")
                        .WithMany("TimeRecord")
                        .HasForeignKey("ChipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportEventManager.Models.Race", "Race")
                        .WithMany("TimeRecords")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportEventManager.Models.Split", "Split")
                        .WithMany("TimeRecord")
                        .HasForeignKey("SplitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chip");

                    b.Navigation("Race");

                    b.Navigation("Split");
                });

            modelBuilder.Entity("SportEventManager.Models.Category", b =>
                {
                    b.Navigation("RaceCategories");

                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("SportEventManager.Models.Chip", b =>
                {
                    b.Navigation("RegistrationChip");

                    b.Navigation("TimeRecord");
                });

            modelBuilder.Entity("SportEventManager.Models.Event", b =>
                {
                    b.Navigation("Races");
                });

            modelBuilder.Entity("SportEventManager.Models.Participant", b =>
                {
                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("SportEventManager.Models.Race", b =>
                {
                    b.Navigation("RaceCategories");

                    b.Navigation("Registrations");

                    b.Navigation("Splits");

                    b.Navigation("TimeRecords");
                });

            modelBuilder.Entity("SportEventManager.Models.Registration", b =>
                {
                    b.Navigation("RegistrationChips");
                });

            modelBuilder.Entity("SportEventManager.Models.Split", b =>
                {
                    b.Navigation("TimeRecord");
                });
#pragma warning restore 612, 618
        }
    }
}
